# .travis.yml
language: android
jdk: oraclejdk7
sudo: false
env:
  global:
  - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
  - ADB_INSTALL_TIMEOUT=10

android:
  components:
    - android-23
    - android-22
    - build-tools-23.0.1
    - build-tools-22.0.1
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-19

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
    - ./gradlew --info clean lint assemble 
    - ./gradlew --info :app:connectedAndroidTest
